### ISSUE TITLE
2.7 View a report of all accounts found in the chart of accounts

### ISSUE THREAD

**Issue by CarsonShattuck** [matthewperiut/seven-elcounting#52]

**Comment by slipperyfishy** [comment]
With how the charts of accounts are already set up, isn't this already completed? Because it's in one spot already, we can work on creating individual ones since there's a requirement to "View either individual accounts and their details or a report of all accounts found in the chart of accounts."

**Comment by CarsonShattuck** [comment]
I believe this is referencing the General Ledger and not the chart of accounts, although im not sure. I am just going to reopen this for now
