### ISSUE TITLE
2.12 You should be able to filter the data in the chart of accounts page using various tokens such as by account number, category, subcategory, amount, etc

### ISSUE THREAD

**Issue by CarsonShattuck** [matthewperiut/seven-elcounting#55]

**Comment by ychawla2000** [comment]
Added queries from just account names to account name, order, account subcateogry, account category, account number, account balance

**Comment by slipperyfishy** [comment]
Completed but I'm leaving it open just in case we have to make edits or completely scrap the filter I made
