### ISSUE TITLE
Auth: Login - if you refresh the page the logout button is in the top left - should only be the logo

### ISSUE THREAD

**Issue by slipperyfishy** [matthewperiut/seven-elcounting#95]
<img width="1717" alt="Screenshot 2024-04-24 at 11 35 53 PM" src="https://github.com/matthewperiut/seven-elcounting/assets/138192109/0b1ffff2-fb20-46da-a058-68cbe681a568">

Should look like this
<img width="1717" alt="Screenshot 2024-04-24 at 11 38 21 PM" src="https://github.com/matthewperiut/seven-elcounting/assets/138192109/d8c5821b-7240-48ee-a9bd-b8d567417333">

**Comment by CarsonShattuck** [comment]
this is not an issue, when the quota is reached and you try to login, it will log you in an as unauthenticated user, try clicking the logo and you will see you can go to the dashboard(im not sure why it doesnt automatically redirect you to dashboard) -- doesnt happen regularly.
